In [1]:
import pandas as pd
import numpy as np

In [17]:
file = 'ionosphere.data'
data = pd.read_csv(file, header=None)
print(data.shape)

(351, 35)


In [18]:
classe_b = data[data.iloc[:, -1] == 'b']
print(classe_b.shape)
classe_g = data[data.iloc[:, -1] == 'g']
print(classe_g.shape)

(126, 35)
(225, 35)


In [21]:
data_classe_b = classe_b.iloc[:, :-1]
print(data_classe_b.shape)
cov_classe_b = np.cov(data_classe_b)
print(cov_classe_b)

(126, 34)
[[ 0.28012466  0.11595781  0.04797851 ... -0.00062636 -0.05663107
   0.0291638 ]
 [ 0.11595781  0.44325444  0.035077   ... -0.01466273  0.01112915
   0.09368152]
 [ 0.04797851  0.035077    0.03474334 ... -0.00377667  0.02049266
   0.03286283]
 ...
 [-0.00062636 -0.01466273 -0.00377667 ...  0.06060606  0.06060606
   0.02343424]
 [-0.05663107  0.01112915  0.02049266 ...  0.06060606  0.45431437
   0.13625132]
 [ 0.0291638   0.09368152  0.03286283 ...  0.02343424  0.13625132
   0.27773196]]


In [22]:
data_classe_g = classe_g.iloc[:, :-1]
print(data_classe_g.shape)
cov_classe_g = np.cov(data_classe_g)
print(cov_classe_g)

(225, 34)
[[0.28317304 0.24055214 0.24016738 ... 0.22575838 0.23605557 0.21201986]
 [0.24055214 0.21989283 0.21117637 ... 0.20522497 0.21427093 0.19386958]
 [0.24016738 0.21117637 0.24253707 ... 0.17510282 0.18575889 0.16829145]
 ...
 [0.22575838 0.20522497 0.17510282 ... 0.21945566 0.22624042 0.20167489]
 [0.23605557 0.21427093 0.18575889 ... 0.22624042 0.23598079 0.20799426]
 [0.21201986 0.19386958 0.16829145 ... 0.20167489 0.20799426 0.18999644]]
