In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Parte 1

## Geração de dados artificiais com as características estatísticas desejadas de covariância.

In [2]:
# Gera dados gaussianos com atributos não-correlacionados
m1 = 5  # Média teórica do atributo 1
sig1 = 1  # Desvio-padrao teorico do atributo 1

m2 = -5  # Média teórica do atributo 2
sig2 = sig1  # Desvio-padrao teorico do atributo 2

m3 = 0  # Média teórica do atributo 3
sig3 = sig1  # Desvio-padrao teorico do atributo 3

N = 5000  # Quantidade de observacoes geradas de cada atributo
X1 = np.random.normal(m1, sig1, N)
X2 = np.random.normal(m2, sig2, N)
X3 = np.random.normal(m3, sig3, N)

Xu = np.vstack((X1, X2, X3))  # Agrupa dados dos atributos em uma unica matriz

# Matriz desejada para os dados
Cd = np.array([[1, 1.8, -0.9], [1.8, 4, 0.6], [-0.9, 0.6, 9]])

print(Xu.shape)
print(Cd.shape)
Cd

(3, 5000)
(3, 3)


array([[ 1. ,  1.8, -0.9],
       [ 1.8,  4. ,  0.6],
       [-0.9,  0.6,  9. ]])

## Método de Choleski para decompor a matriz de covariância desejada e correlacionar os 3 atributos gaussianos inicialmente não correlacionados

In [3]:
R = np.linalg.cholesky(Cd)  # Decomposicao de Cholesky da matriz Cd

Xc = np.dot(R.T, Xu)  # Gera dados com atributos correlacionados com a matriz COV desejada
Xc

array([[-2.63217031,  1.17714759, -1.12486186, ..., -5.89054902,
        -7.40990569,  0.75283929],
       [-6.81713827, -6.15332793, -3.81298822, ..., -3.13046173,
        -6.70619387, -4.509726  ],
       [-1.31418554, -1.76407573, -0.13671372, ...,  0.74654681,
        -0.68214916, -1.05062419]])

# Parte 2

In [5]:
# Aplicacao de PCA aos dados correlacionados gerados no procedimento anterior.
# Estimar a matriz de covariância Cx associada aos dados sintéticos originais na matrix Xc
Cx = np.cov(Xc)  
Cx

array([[ 5.10387395, -0.67134364, -1.17306652],
       [-0.67134364,  7.07964066,  3.23260854],
       [-1.17306652,  3.23260854,  1.6611107 ]])

In [12]:
# Calcular os autovalores e a matriz de autovetores V
# L - vetor com os autovalores 
# V - matriz onde cada coluna é um autovetor
L, V = np.linalg.eig(Cx)
print('Autovalores: ', L)
print('Matriz autovetor: ', V)

Autovalores:  [8.91422773 4.90090755 0.02949002]
Matriz autovetor:  [[ 0.28304754 -0.94633255  0.15600893]
 [-0.85818365 -0.32252178 -0.39937516]
 [-0.428258    0.02084216  0.90341612]]
